### ISSUE TITLE
Navigazione Pagina lezione 

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#1]
Navigabilità pagina lezione:
- successione step 
- posizionare le risorse (link a risorse utili alla lezione)
- posizionare esercizi aggiuntivi
- posizionare bottone form da compilare (accessibile solo agli iscritti)
- posizionare esempi significativi scuole 14/15

**Comment by sirmmo** [comment]
Non mi é chiaro...

**Comment by chiaracio** [comment]
AH NO? COME MAI?
