### ISSUE TITLE
Modifiche al form creazione report di monitoraggio

### ISSUE THREAD

**Issue by luigireggi** [chiaracio/ASOC1516#100]
1) Inserire il titolo del campo CUP: “Codice Unico Progetto (CUP)” (non obbligatorio). - fatto
2) Inserire URL progetto OC e breve testo di spiegazione (MARCO PROPONE TESTO: es. copiare e incollare l'indirizzo della pagina di OC dedicata al progetto dalla barra degli indirizzi... inserire esempio)
3) Inserire spiegazione sotto la mappa. (MARCO PROPONE TESTO. Come si usano gli strumenti: puntatore, area, linea... testo breve ma intenso:)) ).
4) Togliere campo Team da elenco campi da valorizzare.

**Comment by sirmmo** [comment]
- Inserire spiegazione sotto la mappa: Cosa mettiamo di "descrittivo"? :s

**Comment by luigireggi** [comment]
"marco propone testo"

:)

**Comment by sirmmo** [comment]
ah lol! :D

invece:per quanto riguarda il resto, ovvero: puntatore, area, linea, come
lo descriviamo?

On Fri, Jan 22, 2016 at 2:36 PM, luigireggi notifications@github.com
wrote:

> "marco propone testo"
> 
> :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/100#issuecomment-173923287.

## 

Marco Montanari
mail: marco.montanari@gmail.com
office: marco.montanari@labs.it
other: mmo@mmo.it
mobile: +39 3335267086
web: http://www.mmo.it

**Comment by luigireggi** [comment]
"marco propone testo"

:) :)

sennò aspettiamo sett prossima che mi sistemo in the USA

**Comment by luigireggi** [comment]
Direi che su questo ci siamo!
Fatta prova tutto sembra ok
