### ISSUE TITLE
Problemi nell'invio del form report di monitoraggio

### ISSUE THREAD

**Issue by luigireggi** [chiaracio/ASOC1516#101]
1) Quando salva la bozza elimina il nome del progetto
2) Quando invia il nome del progetto non riappare => viene scritto “report” come titolo
3) L’immagine caricata risulta broken una volta inviato. Chiara inserisce su github degli esempi.

**Comment by sirmmo** [comment]
L’immagine caricata risulta broken una volta inviato. Chiara inserisce su github degli esempi

**Comment by chiaracio** [comment]
http://monithon.org/reports/991 ho trovato solo questo esempio sarebbe utile avere dei filtri esposti per regione e tema anche su Monithon (se facile)

**Comment by sirmmo** [comment]
è un pdf... l'hanno caricato come "immagine" ma immagine non è...

On Fri, Jan 22, 2016 at 10:59 AM, chiaracio notifications@github.com
wrote:

> http://monithon.org/reports/991 ho trovato solo questo esempio
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/101#issuecomment-173865849.

## 

Marco Montanari
mail: marco.montanari@gmail.com
office: marco.montanari@labs.it
other: mmo@mmo.it
mobile: +39 3335267086
web: http://www.mmo.it

**Comment by luigireggi** [comment]
beh una immagine può essere in pdf.. o no? :-\

**Comment by luigireggi** [comment]
il form di invio sembra funzionare!

**Comment by luigireggi** [comment]
rimane il problema di visualizzare le info sull'autore
