### ISSUE TITLE
Forum ultimo aggiornamento

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#103]
E' possibile @sirmmo aggiungere una colonna che indica l'ultimo aggiornamento già qui?
http://www.ascuoladiopencoesione.it/forums/forum/asoc-2015-2016/

**Comment by sirmmo** [comment]
ultimo aggiornamento è praticamente impossibile. Però ho attivato il "c'è roba nuova".

**Comment by sirmmo** [comment]
http://www.ascuoladiopencoesione.it/forums/forum/asoc-2015-2016/
