### ISSUE TITLE
Scheda di monitoraggio

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#118]
@sirmmo 
ho fatto test su Monithon. Di seguito le cose non funzionanti. 
ho fatto test: 
- non obbliga ad inserire i dati ma si possono modificare
- l'immagine del profilo risulta broken e non si può caricare
  **\- CERCA UN INDIRIZZO:** è necessario spostare la scritta sopra la mappa non sotto altrimenti non si capisce cosa fare". Dopo "posizione" scrivere tra ():
  # Scrivere indirizzo (es: via Nazionale 17, Roma) 
  # Premere Invio 
  # Apparirà un messaggio automatico, premere OK
  # Adesso potrete posizionare il marker nel luogo preciso del progetto monitorato
  # Per posizionare il marker: cliccare una volta sul marker nel menu a sinistra,  trascinarlo nel punto desiderato, rilasciarlo con un altro click. 
- aumentare spazio tra i campi per renderli più leggibili
- Url OpenCoesione: srivere URL maiuscolo
- nel giudizio sintetico togliere "&" e usare "e" normale
- Carimamento immagine: usare un colore diverso su "Clicca qui" 
- l'immagine si carica ma risulta "broken" 
  <img width="428" alt="screen shot 2016-02-23 at 10 53 28" src="https://cloud.githubusercontent.com/assets/6087317/13247835/d05b8d28-da1b-11e5-99ab-92a296582f45.png">

**Comment by sirmmo** [comment]
risolte le varie questioni del report.

il problem adell'immagine non so posizionalro, in quanto :
[image: Inline image 1]
magari nella pagina di caricaemnto metto una speigazione?

M

2016-02-23 11:02 GMT+01:00 chiaracio notifications@github.com:

> ho fatto test su Monithon. Di seguito le cose non funzionanti.
> ho fatto test:
> - non obbliga ad inserire i dati ma si possono modificare
> - l'immagine del profilo risulta broken e non si può caricare _\- CERCA
>   UN INDIRIZZO:_ è necessario spostare la scritta sopra la mappa non
>   sotto altrimenti non si capisce cosa fare". Dopo "posizione" scrivere tra
>   ():
> - Scrivere indirizzo (es: via Nazionale 17, Roma)
> - Premere Invio
> - Apparirà un messaggio automatico, premere OK
> - Adesso potrete posizionare il marker nel luogo preciso del progetto
>   monitorato
> - Per posizionare il marker: cliccare una volta sul marker nel menu a
>   sinistra, trascinarlo nel punto desiderato, rilasciarlo con un altro click.
> - aumentare spazio tra i campi per renderli più leggibili
> - Url OpenCoesione: srivere URL maiuscolo
> - nel giudizio sintetico togliere "&" e usare "e" normale
> - ## Carimamento immagine: usare un colore diverso su "Clicca qui"
>   
>   l'immagine si carica ma risulta "broken"
>   [image: screen shot 2016-02-23 at 10 53 28]
>   
>   ## https://cloud.githubusercontent.com/assets/6087317/13247835/d05b8d28-da1b-11e5-99ab-92a296582f45.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/118.

## 

Marco Montanari
mail: marco.montanari@gmail.com
office: marco.montanari@labs.it
other: mmo@mmo.it
mobile: +39 3335267086
web: http://www.mmo.it

**Comment by chiaracio** [comment]
@sirmmo cose rimaste da fare:
1. Profilo utente: togliere immagine, importare dati da ASOC o rendere obbligatoria la compilazione quando non ASOC
2. Report: 
- aggiugnere un separatore per rendere distinguibili chiaramente i campi
- sistemare BUG caricamento IMG Firefox
