### ISSUE TITLE
Test REport lEzione 4 - Visualizzazione "interna"

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#132]
@sirmmo 
Qui visualizzazione di prova interna: 
http://www.ascuoladiopencoesione.it/lesson_4_form/21897/
1. La parte di domande e risposte non si vede
2. Non si vede immagine ma c'è solo scritto "Array"
Fammi sapere

**Comment by sirmmo** [comment]
form: http://ascuoladiopencoesione.it/form-lezione-4
