### ISSUE TITLE
Account amministratori provvisori per approvazione report

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#139]
Servirebero account redazione upgrade affinchè possano approvare report scuole:
- cinzia roma: cinzia.roma86@gmail.com
- antonella ciociola: anto.ciociola@gmail.com 
- francesca de chiara: francesca.dechiara@gmail.com 
- paola liliana buttiglione: paola.liliana.buttiglione@gmail.com

**Comment by sirmmo** [comment]
cinzia roma: username: cinzia.roma86@gmail.com password: m0n1thon
antonella ciociola: username: anto.ciociola@gmail.com password: m0n1thon
francesca de chiara: username: FrancescaDeChiara password: m0n1thon (utente c'era già)
paola liliana buttiglione: username: PaolaLilianaButtiglione password: m0n1thon (utente c'era già)

**Comment by chiaracio** [comment]
grazie,

procedo.

C.

2016-03-24 12:31 GMT+01:00 Marco Montanari notifications@github.com:

> cinzia roma: username: cinzia.roma86@gmail.com password: m0n1thon
> antonella ciociola: username: anto.ciociola@gmail.com password: m0n1thon
> francesca de chiara: username: FrancescaDeChiara password: m0n1thon
> (utente c'era già)
> paola liliana buttiglione: username: PaolaLilianaButtiglione password:
> m0n1thon (utente c'era già)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/139#issuecomment-200797334

## 

Chiara Ciociola
