### ISSUE TITLE
Aggiunta testo descrittivo campi report standard

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#140]
E' possibile aggiungere alle domande del report standard il testo in grassetto 

Punti di forza (cosa ti è piaciuto **del progetto monitorato?**)
Debolezze (difficoltà riscontrate **nell'attuazione/realizzazione del progetto monitorato?**) 
Rischi futuri **per il progetto monitorato**
Soluzioni ed idee da proporre **per il progetto monitorato**

**Comment by sirmmo** [comment]
fixed #140
