### ISSUE TITLE
editor di testo nella descrizione progetto

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#146]
é possibile aggiungerlo nella parte di compilazione?

**Comment by sirmmo** [comment]
intendi editor wysiwyg?

**Comment by chiaracio** [comment]
si

2016-04-07 11:14 GMT+02:00 Marco Montanari notifications@github.com:

> intendi editor wysiwyg?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/146#issuecomment-206777300

## 

Chiara Ciociola

**Comment by sirmmo** [comment]
ok!
