### ISSUE TITLE
Icone approvazione/bozza

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#147]
Se rimetto in bozza un report NON diventa giallo

**Comment by sirmmo** [comment]
intendi un report finalizzato non validato, giusto? perchè mi sa che quella opzione non l'avevamo prevista... posso aggiungere un'icona... quello che puoi fare è togliere l'approvazione, e ho testato ora:funziona. può essere che cliccando "back" non ricarichi la pagina ma prenda la versione in memoria...

**Comment by chiaracio** [comment]
ne possiamo parlare a voce???

Il giorno 7 aprile 2016 11:13, Marco Montanari notifications@github.com
ha scritto:

> intendi un report finalizzato non validato, giusto? perchè mi sa che
> quella opzione non l'avevamo prevista... posso aggiungere un'icona...
> quello che puoi fare è togliere l'approvazione, e ho testato ora:funziona.
> può essere che cliccando "back" non ricarichi la pagina ma prenda la
> versione in memoria...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/147#issuecomment-206776419

## 

Chiara Ciociola

**Comment by chiaracio** [comment]
Non capisco come si rimette in bozza!
