### ISSUE TITLE
Navigazione blog delle classi 

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#20]
@sirmmo prevedere una modalità di navigazione delle classi per categorie incociate:
- inizialmente solo mappa delle scuole + reti + tabella con filtri esposti per territorio e nome scuola
- poi questa mappa servirà per navigazione del blog dei Team. Prevediamo quindi che dove ci sono due team ci sia un segnaposto con il numero di calssi della scuola scelta e i rispettivi link al blog
- i filtri esposti sotto si arricchiscono man mano dei nuovi elementi (link al blog, link al progetto OC monitorato, link al twitter, tema di OC etc...)

**Comment by chiaracio** [comment]
@sirmmo nel link della mappa si vedete anche il dataset non riesco a modificare

**Comment by chiaracio** [comment]
http://www.clipular.com/c/5748124076212224.png?k=Lm296DTUvk56XeTPBJL6GhkHqok

**Comment by sirmmo** [comment]
http://www.ascuoladiopencoesione.it/blog-scuole-1516/

**Comment by sirmmo** [comment]
http://www.ascuoladiopencoesione.it/blog-scuole-1516/?team=608

**Comment by sirmmo** [comment]
http://www.ascuoladiopencoesione.it/blog-scuole-1516/?team=608&post=17303

**Comment by chiaracio** [comment]
@sirmmo 
1. qui: http://www.ascuoladiopencoesione.it/blog-scuole-1516/
- sistemare il menu acciaccato in alto a dx
- creare un riquadro di mappa più alto in modo che la cartina dell'Italia appaia più grande. Eventualmente possiamo anche eliminare il full width e fare un riquadro più "quadrato" e rispondente alla forma dello stivale, e mi raccomando alla Sicilia :)
- aggiungere ai menu a tendina di filtro di ricerca una frase guida alla navigazione: "Filtra le scuole per Regione"; "Filtra le scuole per Tema" 
- nei singoli riquadri delle classi aggiungere anche nell'anteprima città e provincia
- i post appariranno in ordine di pubblicazione? 
- in alcuni quadratini non appare il nome scuola, come mai?

**Comment by chiaracio** [comment]
@sirmmo 
- MAPPA: si può usare questo layer?  https://asoc.cartodb.com/viz/637dcc04-8060-11e4-b185-0e853d047bba/public_map
- Colore dei segnaposto: 
  ROSSO R 235 G 107 B 89 #ec6858
  AZZURRO R 69 G 157 B 160 #419da4

**Comment by chiaracio** [comment]
pagina singola team: http://www.ascuoladiopencoesione.it/blog-scuole-1516/?team=608 
- sistemare il menu acciaccato in alto a dx
- togliere righino nero sotto il filtro di ricerca
- nel titolo del singolo post inserire: titolo del report 
- nei dati del profilo team laterale aggiugnere: titolo del progetto OC scelto con link a OC, tema + edic + associazione di affiancamento, è possibile?
- nel footer appare il plug in dei cookies tutto sovrapposto ed illeggibile

**Comment by chiaracio** [comment]
Pagina report di lezione: http://www.ascuoladiopencoesione.it/blog-scuole-1516/?team=608&post=17303 
- sistemare il menu acciaccato in alto a dx
- togliere righino nero sotto il filtro di ricerca
-  nel footer appare il plug in dei cookies tutto enorme nel suo profondo blu asoc
- nei dati del profilo team laterale aggiugnere: titolo del progetto OC scelto con link a OC, tema + edic + associazione di affiancamento, è possibile?

**Comment by chiaracio** [comment]
- togliere lo zoom come mouse wheel
- pulsante + e meno è come "over" sulla pagina 
- il filtro della mappa modificarsi in accordo con i filtri selezionati dal menu a tendina 
- cambiare testo del link "tutte le scuole" con il testo "torna al blog delle scuole"
