### ISSUE TITLE
aggiornamento pagina cos'è ASOC 

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#24]
http://www.ascuoladiopencoesione.it/cose-a-scuola-di-open-coesione/ 

AARGHH :) @gianguaz

**Comment by sirmmo** [comment]
what?? :S

2015-11-13 12:35 GMT+01:00 chiaracio notifications@github.com:

> http://www.ascuoladiopencoesione.it/cose-a-scuola-di-open-coesione/
> 
> AARGHH :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/24.

## 

Marco Montanari
mail: marco.montanari@gmail.com
office: marco.montanari@labs.it
other: mmo@mmo.it
mobile: +39 3335267086
web: http://www.mmo.it

**Comment by chiaracio** [comment]
scusa era per gianmarco da aggiornare scusate :(

**Comment by chiaracio** [comment]
Scusate l'alert esagerato. E' necessario aggiornare la pagina di cos'è ASOC al più presto perchè c'è ancora il video di documentazione precedente. magari mettiamo riferimento alla webserie che è utilissima!

**Comment by chiaracio** [comment]
questa è pronta? @gianguaz

**Comment by gianguaz** [comment]
Fatto @chiaracio
