### ISSUE TITLE
Profilo Team Scuola - campi profilo

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#30]
Eliminare campi:
flag editor visuale (io lo vedo quando fccio impersonate)
scorciatoie da tastiera (io lo vedo quando fccio impersonate)
precompilazione con miei dati inventati (tipo twitter @ciocio :DDD) o forse appare perchè quelli sono i dati del mio profilo gli altri non lo vedono?

**Comment by chiaracio** [comment]
@sirmmo 
- Aggiungere qui il link per il cambio password 
- sistemare il menu sfalzato in alto

**Comment by sirmmo** [comment]
fixed!
