### ISSUE TITLE
Cambio password utenti

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#34]
Dove andare per cambiare la password per gli utenti?

**Comment by sirmmo** [comment]
ALLELUJA! dopo aver provato TUTTI i plugin del circondario ho trovato.

http://www.ascuoladiopencoesione.it/user-profile si può cambiare la password..

**Comment by chiaracio** [comment]
Inserire link in pagina profilo

**Comment by chiaracio** [comment]
Come si arriva a questa schermata dal profilo utente? @sirmmo
