### ISSUE TITLE
FORUM (accesso di una classe al vecchio forum)

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#36]
@sirmmo 

una classe ha scritto questo post su forum:
http://www.ascuoladiopencoesione.it/forums/topic/homework/page/3/#post-17377 

che però è finito nel forum Homework progettare dello scorso anno.

Questo è un errore dovuto alla navigazione, perchè nelle breadcrumbs cliccando su Forum si va al vecchio forum. Non possiamo avere pagine aperte che non vogliamo che siano cliccate.

**Comment by sirmmo** [comment]
chiusi tutti i forum vecchi

**Comment by chiaracio** [comment]
CHIUSI = VISIBILI ai vecchi link MA senza interazioni?

C.

2015-11-26 19:06 GMT+01:00 Marco Montanari notifications@github.com:

> chiusi tutti i forum vecchi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiaracio/ASOC1516/issues/36#issuecomment-159970707.

## 

Chiara Ciociola

**Comment by sirmmo** [comment]
yes

**Comment by chiaracio** [comment]
Marco così non va bene comunque perchè non si capisce dove andare. 

Ci ha già scritto una docente che non comprende bene. 

TI copio qui la mail: 

 Gent.le Team,
leggo con piacere la tempestiva risposta e comunico che avevo già eseguito da sola tutti i passaggi ma non riesco a trovare qualcosa di diverso da quello che consulto senza le credenziali. Vorrei cambiare la password e possibilmente la login e capire meglio come attivare l'account del team classe. Mi sono infine iscritta al forum, non indicato chiaramente in piattaforma,e ho notato che non è riferito solo all'anno in corso ma ad interventi delle esperienze precedenti. E' possibile?
Grazie, non vorrei sembrare noiosa, ma il progetto è intrigante e realmente innovativo e non mi piacerebbe disattendere le aspettative di tutti.
Cordiali saluti
Silvana Chiumeo

**Comment by sirmmo** [comment]
risolto

**Comment by chiaracio** [comment]
@sirmmo 
cliccando su link forum nella breadcrumb si apre questa pagina http://www.ascuoladiopencoesione.it/forums/. Sistemare la tabella in modo che non si sovrappongano le scritte "partecipanti" e "articoli"
