### ISSUE TITLE
visualizzazione report di lezione

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#42]
come appare?

**Comment by sirmmo** [comment]
http://www.ascuoladiopencoesione.it/lesson_1_form/report-lezione-1-imperatore-del-giappone-2/

**Comment by chiaracio** [comment]
@sirmmo 
- aumentare lo spazio bianco tra il titolo e la linea del menu 
- campi relativi al progetto scelto su OC: si può fare un box con tutti i dati del progetto in evidenza? Tipo quello azzurrino in alto a dx qui: http://www.ascuoladiopencoesione.it/portfolio-articoli/lezione-progettare-1516/? Gli stessi devono apparire nei dati del profilo utente che appare nella colonna laterale del report di lezione visibile dal blog scuole
- aggiungere un pulsante "salva in pdf" o simile una volta che il report è pubblicato? 
- aggiungere link al report pubblicato nel formato "blog"?
