### ISSUE TITLE
Blog Lezione 1 - Il naso nella conchiglia

### ISSUE THREAD

**Issue by luigireggi** [chiaracio/ASOC1516#52]
http://www.ascuoladiopencoesione.it/blog-scuole-1516/?team=1340&post=18028
Rimangono pezzetti di codice dentro al testo finale

Es. [caption id="attachment_18235" align="aligncenter" width="462"]

**Comment by sirmmo** [comment]
fixed

**Comment by luigireggi** [comment]
Sulla destra rimane
string(13) "(^|,)119(,|$)" array(4) { ["nome_ref"]=> array(1) { [0]=> string(9) "Guglielmo" } ["cognome_ref"]=> array(1) { [0]=> string(8) "Trupiano" } ["mail"]=> array(1) { [0]=> string(17) "trupiano@unina.it" } ["id_asoc"]=> array(1) { [0]=> string(30) "3,37,39,95,116,117,118,119,181" } }

**Comment by luigireggi** [comment]
CIPE è comitato interministeriale per la programmazione economica
non comitato internazionale :)))
