### ISSUE TITLE
FORUM per lezione + sezione "tecnica" per uso sitoweb

### ISSUE THREAD

**Issue by chiaracio** [chiaracio/ASOC1516#7]
Riattivare una sezione forum NUOVA con aggiunta di sezione tecnica per uso sito web con:
- registrazione
- compilazione report di lezione (istruzioni per il salvataggio in bozze)

**Comment by sirmmo** [comment]
forum up and running.

**Comment by chiaracio** [comment]
ma se rispondo qua vale come se rispondo su git hub? cioè lo aggiorna?

**Comment by chiaracio** [comment]
La sezione forum si vede male ed è ordinata al contrario
http://www.clipular.com/c/4966191759097856.png?k=KsTvoEdrwEoVg0L5v98rjpNdRZQ

**Comment by chiaracio** [comment]
Aggiungere parte descrittiva alla pagina forum @sirmmo
